"""
CS550 – GNN on Cora  |  Role 3: Explainability
"""

import streamlit as st
import streamlit.components.v1 as components
import torch
import numpy as np
import pandas as pd
from pathlib import Path
import json
import sys
import os

# ── Environment & Paths — Collaborative Bridge ───────────────────────────
REPO_PATH = os.path.join(os.getcwd(), ".")
if REPO_PATH not in sys.path:
    sys.path.append(REPO_PATH)

st.set_page_config(
    page_title="CS550 · GNN Explorer",
    page_icon="🔬",
    layout="wide",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif !important; }
code, pre { font-family: 'JetBrains Mono', monospace !important; }
#MainMenu, footer, header { display: none !important; }
/* Remove ALL default Streamlit padding */
.block-container { padding-top: 1rem !important; padding-bottom: 0.5rem !important; }
[data-testid="stVerticalBlock"] { gap: 0.4rem !important; }
/* Tighten metric blocks */
[data-testid="stMetric"] { padding: 0.3rem 0 !important; }
[data-testid="metric-container"] { padding: 0 !important; }
/* Tighten divider */
hr { margin: 0.4rem 0 !important; }
/* Reduce gap above tabs */
[data-testid="stTabs"] { margin-top: 0 !important; }
/* Tighten column gaps */
[data-testid="stHorizontalBlock"] { gap: 1rem !important; }
/* Reduce subheader margins */
h2, h3 { margin-top: 0.3rem !important; margin-bottom: 0.3rem !important; }
/* Remove top space in tab panels */
[data-testid="stTabs"] [data-baseweb="tab-panel"] { padding-top: 0.6rem !important; }
</style>
""", unsafe_allow_html=True)

# ── Constants ──────────────────────────────────────────────────────────────
CLASSES = [
    "Case Based", "Genetic Algorithms", "Neural Networks",
    "Probabilistic Methods", "Reinforcement Learning", "Rule Learning", "Theory",
]
COLORS = ["#4361ee","#3a86ff","#06d6a0","#ffd166","#ef476f","#8338ec","#ff6b6b"]

# ── Collaborator Integration — Live Metrics ──────────────────────────────
@st.cache_data
def load_team_metrics():
    """Reads the results CSV generated by Member 2's training scripts."""
    paths = [
        Path("outputs/results.csv"),
        Path("results.csv"),
        Path(os.path.join(REPO_PATH, "outputs/results.csv")),
        Path(os.path.join(REPO_PATH, "selected_plots/results.csv")),
    ]
    dfs = []
    for p in paths:
        if p.exists():
            try:
                df = pd.read_csv(p)
                df.columns = [c.strip().lower() for c in df.columns]
                # Harmonize common divergent names
                rename_map = {'f-measure': 'f1', 'auc': 'auc_roc', 'auc-roc': 'auc_roc'}
                df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})
                dfs.append(df)
            except: continue
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

def get_metric_val(df, model_name, metric_key, is_pct=False, default="--"):
    if df.empty or 'model' not in df.columns or model_name not in df['model'].values:
        return default
    key_map = {
        'accuracy': ['accuracy', 'Accuracy'], 'f1': ['f1', 'F-measure', 'F1-Score'],
        'precision': ['precision', 'Precision'], 'recall': ['recall', 'Recall'],
        'auc_roc': ['auc_roc', 'AUC-ROC']
    }
    possible_keys = key_map.get(metric_key, [metric_key])
    actual_key = next((k for k in possible_keys if k in df.columns), None)
    if not actual_key: return default
    val = df[df['model'] == model_name][actual_key].values[0]
    try:
        return f"{float(val)*100:.1f}%" if is_pct else f"{float(val):.3f}"
    except: return str(val)

def get_plot_path(filename):
    """Search for plot files in collaborator repository or local output."""
    paths = [
        Path(f"selected_plots/{filename}"),
        Path(f"outputs/{filename}"),
        Path(os.path.join(REPO_PATH, f"selected_plots/{filename}")),
        Path(os.path.join(REPO_PATH, f"outputs/{filename}"))
    ]
    for p in paths:
        if p.exists(): return str(p)
    return None

# ── Load model & data ──────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading Cora dataset & GNN models…")
def load_everything():
    from data_loader import load_cora
    from models import GAT
    from torch_geometric.nn import VGAE
    from train_link import VGAEEncoder
    
    # Load dataset
    dataset, data = load_cora(root="data/Cora")

    # 1. Initialize Node Model (GAT)
    gat_model = GAT(
        in_channels=dataset.num_features, 
        hidden_per_head=8, 
        out_channels=dataset.num_classes, 
        heads=8,
        dropout=0.6
    )
    
    # 2. Initialize Link Model (VGAE)
    vgae_model = VGAE(
        encoder=VGAEEncoder(
            in_channels=dataset.num_features,
            hidden_channels=64,
            out_channels=32,
        )
    )
    
    # Load Weights
    gat_weights = Path("models/gat_best.pth")
    vgae_weights = Path("models/vgae_best.pth")
    
    loaded_gat = False
    if gat_weights.exists():
        gat_model.load_state_dict(torch.load(gat_weights, map_location="cpu", weights_only=True))
        loaded_gat = True
    
    loaded_vgae = False
    if vgae_weights.exists():
        vgae_model.load_state_dict(torch.load(vgae_weights, map_location="cpu", weights_only=True))
        loaded_vgae = True
    
    gat_model.eval()
    vgae_model.eval()
    return data, gat_model, vgae_model, loaded_gat, loaded_vgae

@st.cache_data(show_spinner=False)
def infer(_data, _model):
    with torch.no_grad():
        return torch.softmax(_model(_data.x, _data.edge_index), dim=1).numpy()

# ── 3-D ego-network — photorealistic space scene ─────────────────────────
def graph_html(data, probs, node_id):
    ei     = data.edge_index.numpy()
    labels = data.y.numpy()

    # 2-hop ego network for richer graph
    hop1 = ei[1][ei[0] == node_id].tolist()[:40]
    included = {node_id} | set(hop1)
    for n in hop1[:12]:
        included.update(ei[1][ei[0] == n].tolist()[:5])
    included = list(included)[:65]
    imap = {n: i for i, n in enumerate(included)}

    nodes = [{"id": imap[n], "orig": int(n), "cls": int(labels[n]),
               "color": COLORS[int(labels[n])],
               "label": CLASSES[int(labels[n])],
               "conf": float(probs[n, probs[n].argmax()]),
               "isTarget": n == node_id} for n in included]
    edges = [{"s": imap[int(s)], "t": imap[int(t)]}
             for s, t in zip(ei[0], ei[1])
             if int(s) in imap and int(t) in imap]

    pred_cls = CLASSES[int(probs[node_id].argmax())]
    pred_clr = COLORS[int(probs[node_id].argmax())]

    legend_rows = "".join(
        f'<div style="display:flex;align-items:center;gap:6px;">'
        f'<div style="width:9px;height:9px;border-radius:50%;background:{COLORS[i]};'
        f'box-shadow:0 0 6px {COLORS[i]};"></div>'
        f'<span>{cls}</span></div>'
        for i, cls in enumerate(CLASSES)
    )

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ background:#060818; overflow:hidden; font-family:Inter,system-ui,sans-serif; }}
canvas {{ display:block; }}
#info {{
  position:absolute; bottom:14px; left:14px;
  background:rgba(10,12,30,0.85); border:1px solid rgba(255,255,255,0.1);
  border-radius:10px; padding:10px 14px; font-size:11.5px; color:#94a3b8;
  line-height:1.7; backdrop-filter:blur(10px);
}}
#legend {{
  position:absolute; top:14px; left:14px;
  background:rgba(10,12,30,0.85); border:1px solid rgba(255,255,255,0.1);
  border-radius:10px; padding:10px 14px; font-size:10.5px; color:#94a3b8;
  line-height:1.9; backdrop-filter:blur(10px);
}}
#controls {{
  position:absolute; top:14px; right:14px;
  background:rgba(10,12,30,0.75); border:1px solid rgba(255,255,255,0.08);
  border-radius:10px; padding:8px 14px; font-size:10px; color:#64748b;
  text-align:right; line-height:1.9; backdrop-filter:blur(8px);
}}
#tip {{
  position:absolute; background:rgba(10,12,30,0.95); color:#e2e8f0;
  border:1px solid rgba(255,255,255,0.12); border-radius:8px;
  padding:8px 12px; font-size:11.5px; pointer-events:none; display:none;
  line-height:1.6; box-shadow:0 8px 32px rgba(0,0,0,0.5);
}}
</style></head><body>
<div id="legend">
  <div style="font-size:9px;font-weight:700;letter-spacing:1.2px;color:#475569;margin-bottom:6px;text-transform:uppercase;">Categories</div>
  {legend_rows}
</div>
<div id="info">
  Node <strong style="color:#e2e8f0;">{node_id}</strong> &nbsp;·&nbsp;
  <span style="color:{pred_clr};font-weight:600;">{pred_cls}</span><br/>
  {len(nodes)} nodes &nbsp;·&nbsp; {len(edges)} edges
</div>
<div id="controls">Drag to rotate<br>Scroll to zoom<br>Hover for info</div>
<div id="tip"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
<script>
const NODES = {json.dumps(nodes)};
const EDGES = {json.dumps(edges)};
const W = innerWidth, H = innerHeight;

const renderer = new THREE.WebGLRenderer({{ antialias: true, alpha: false }});
renderer.setSize(W, H);
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.body.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x060818);
scene.fog = new THREE.FogExp2(0x060818, 0.0025);

const cam = new THREE.PerspectiveCamera(52, W / H, 0.5, 3000);
cam.position.set(0, 30, 230);

// ─── Glow sprite texture ───────────────────────────────────────────────────
function makeGlowTex(hexColor, size=128) {{
  const c = document.createElement('canvas');
  c.width = c.height = size;
  const ctx = c.getContext('2d');
  const r = parseInt(hexColor.slice(1,3),16);
  const g = parseInt(hexColor.slice(3,5),16);
  const b = parseInt(hexColor.slice(5,7),16);
  const grad = ctx.createRadialGradient(size/2,size/2,0,size/2,size/2,size/2);
  grad.addColorStop(0,   `rgba(${{r}},${{g}},${{b}},1.0)`);
  grad.addColorStop(0.15,`rgba(${{r}},${{g}},${{b}},0.8)`);
  grad.addColorStop(0.4, `rgba(${{r}},${{g}},${{b}},0.3)`);
  grad.addColorStop(0.7, `rgba(${{r}},${{g}},${{b}},0.08)`);
  grad.addColorStop(1,   `rgba(${{r}},${{g}},${{b}},0.0)`);
  ctx.fillStyle = grad;
  ctx.fillRect(0,0,size,size);
  return new THREE.CanvasTexture(c);
}}

// ─── Stars ────────────────────────────────────────────────────────────────
(function addStars() {{
  const geo = new THREE.BufferGeometry();
  const count = 2000;
  const pts = new Float32Array(count * 3);
  for (let i = 0; i < count * 3; i++) pts[i] = (Math.random() - 0.5) * 1800;
  geo.setAttribute('position', new THREE.BufferAttribute(pts, 3));
  const mat = new THREE.PointsMaterial({{
    color: 0xffffff, size: 0.9, transparent: true, opacity: 0.55,
    sizeAttenuation: true
  }});
  scene.add(new THREE.Points(geo, mat));
}})();

// ─── Lighting ────────────────────────────────────────────────────────────
scene.add(new THREE.AmbientLight(0x1a2040, 2.5));
const sun = new THREE.DirectionalLight(0xffffff, 1.2);
sun.position.set(120, 200, 100);
sun.castShadow = true;
sun.shadow.mapSize.set(1024, 1024);
scene.add(sun);
// coloured fill lights
const pl1 = new THREE.PointLight(0x4361ee, 1.8, 400); pl1.position.set(-80, 60, 0); scene.add(pl1);
const pl2 = new THREE.PointLight(0x06d6a0, 1.2, 350); pl2.position.set(80, -60, 50); scene.add(pl2);
const pl3 = new THREE.PointLight(0x8338ec, 0.8, 300); pl3.position.set(0, 100, -80); scene.add(pl3);

// ─── Force layout ─────────────────────────────────────────────────────────
const pos = NODES.map((_, i) => {{
  const phi = Math.acos(-1 + (2 * i) / NODES.length);
  const theta = Math.sqrt(NODES.length * Math.PI) * phi;
  return new THREE.Vector3(
    100 * Math.sin(phi) * Math.cos(theta),
    100 * Math.sin(phi) * Math.sin(theta),
    100 * Math.cos(phi)
  );
}});
const vel = NODES.map(() => new THREE.Vector3());
for (let it = 0; it < 140; it++) {{
  for (let i = 0; i < NODES.length; i++)
    for (let j = i + 1; j < NODES.length; j++) {{
      const d = pos[i].clone().sub(pos[j]);
      const dist = Math.max(d.length(), 0.5);
      const f = d.normalize().multiplyScalar(1400 / (dist * dist));
      vel[i].add(f); vel[j].sub(f);
    }}
  EDGES.forEach(e => {{
    const d = pos[e.t].clone().sub(pos[e.s]);
    const dist = d.length();
    const f = d.normalize().multiplyScalar((dist - 40) * 0.055);
    vel[e.s].add(f); vel[e.t].sub(f);
  }});
  for (let i = 0; i < NODES.length; i++) {{
    vel[i].multiplyScalar(0.78);
    pos[i].add(vel[i]);
  }}
}}

// ─── Edges — glowing tubes ────────────────────────────────────────────────
EDGES.forEach(e => {{
  const isHL = NODES[e.s].isTarget || NODES[e.t].isTarget;
  const curve = new THREE.LineCurve3(pos[e.s], pos[e.t]);

  // Core tube
  const tubeGeo = new THREE.TubeGeometry(curve, 1, isHL ? 0.55 : 0.25, 4, false);
  const hexClr  = isHL ? '#4361ee' : '#334155';
  const clrInt  = parseInt(hexClr.replace('#',''), 16);
  const tubeMat = new THREE.MeshBasicMaterial({{
    color: clrInt, transparent: true, opacity: isHL ? 0.85 : 0.5
  }});
  scene.add(new THREE.Mesh(tubeGeo, tubeMat));

  // Outer glow tube (wider, dimmer)
  if (isHL) {{
    const glowGeo = new THREE.TubeGeometry(curve, 1, 1.6, 4, false);
    const glowMat = new THREE.MeshBasicMaterial({{
      color: 0x4361ee, transparent: true, opacity: 0.12
    }});
    scene.add(new THREE.Mesh(glowGeo, glowMat));
  }}
}});

// ─── Nodes — spheres + glow halos ─────────────────────────────────────────
const meshes = [];
NODES.forEach((n, i) => {{
  const r     = n.isTarget ? 7.5 : (n.conf > 0.85 ? 4.0 : 3.0);
  const clrInt = parseInt(n.color.replace('#',''), 16);

  // Core sphere
  const geo = new THREE.SphereGeometry(r, 32, 32);
  const mat = new THREE.MeshPhongMaterial({{
    color: clrInt,
    emissive: clrInt,
    emissiveIntensity: n.isTarget ? 0.55 : 0.25,
    shininess: 80,
    specular: 0xffffff,
  }});
  const mesh = new THREE.Mesh(geo, mat);
  mesh.position.copy(pos[i]);
  mesh.castShadow = true;
  mesh.userData = n;
  scene.add(mesh);
  meshes.push(mesh);

  // Glow halo sprite
  const spriteSize = n.isTarget ? 52 : 28;
  const spriteMat = new THREE.SpriteMaterial({{
    map: makeGlowTex(n.color, 128),
    transparent: true,
    blending: THREE.AdditiveBlending,
    depthWrite: false,
    opacity: n.isTarget ? 0.85 : 0.55,
  }});
  const sprite = new THREE.Sprite(spriteMat);
  sprite.scale.set(spriteSize, spriteSize, 1);
  sprite.position.copy(pos[i]);
  scene.add(sprite);

  // Extra outer ring for target node
  if (n.isTarget) {{
    const ringGeo = new THREE.TorusGeometry(12, 0.8, 8, 64);
    const ringMat = new THREE.MeshBasicMaterial({{
      color: clrInt, transparent: true, opacity: 0.6
    }});
    const ring = new THREE.Mesh(ringGeo, ringMat);
    ring.position.copy(pos[i]);
    ring.rotation.x = Math.PI / 2;
    scene.add(ring);
  }}
}});

// ─── Tooltip ──────────────────────────────────────────────────────────────
const tip = document.getElementById('tip');
const ray = new THREE.Raycaster();
const mouse = new THREE.Vector2();
renderer.domElement.addEventListener('mousemove', e => {{
  mouse.x = (e.clientX / W) * 2 - 1;
  mouse.y = -(e.clientY / H) * 2 + 1;
  ray.setFromCamera(mouse, cam);
  const hits = ray.intersectObjects(meshes);
  if (hits.length) {{
    const n = hits[0].object.userData;
    tip.style.display = 'block';
    tip.style.left    = e.clientX + 14 + 'px';
    tip.style.top     = e.clientY - 10 + 'px';
    tip.innerHTML = `<strong style="color:#e2e8f0;">Node ${{n.orig}}</strong><br>
      <span style="color:${{n.color}};font-weight:600;">${{n.label}}</span><br>
      <span style="color:#64748b;font-size:10.5px;">${{(n.conf*100).toFixed(1)}}% confidence</span>`;
    renderer.domElement.style.cursor = 'pointer';
  }} else {{
    tip.style.display = 'none';
    renderer.domElement.style.cursor = 'grab';
  }}
}});

// ─── Orbit controls ───────────────────────────────────────────────────────
let isDragging = false, lastX = 0, lastY = 0, rotY = 0.3, rotX = 0.15;
const RADIUS = 230;
renderer.domElement.addEventListener('mousedown', e => {{
  isDragging = true; lastX = e.clientX; lastY = e.clientY;
  renderer.domElement.style.cursor = 'grabbing';
}});
renderer.domElement.addEventListener('mouseup', () => {{
  isDragging = false; renderer.domElement.style.cursor = 'grab';
}});
renderer.domElement.addEventListener('mousemove', e => {{
  if (!isDragging) return;
  rotY += (e.clientX - lastX) * 0.004;
  rotX += (e.clientY - lastY) * 0.003;
  rotX  = Math.max(-1.3, Math.min(1.3, rotX));
  lastX = e.clientX; lastY = e.clientY;
}});
renderer.domElement.addEventListener('wheel', e => {{
  e.preventDefault();
  e.stopPropagation();
  cam.position.z = Math.max(80, Math.min(500, cam.position.z + e.deltaY * 0.35));
}}, {{ passive: false }});

// Block page scroll from reaching parent iframe
document.addEventListener('wheel', e => e.preventDefault(), {{ passive: false }});

// ─── Animate ──────────────────────────────────────────────────────────────
let t = 0;
(function loop() {{
  requestAnimationFrame(loop);
  t += 0.004;
  if (!isDragging) rotY += 0.0022;

  cam.position.x = Math.sin(rotY) * RADIUS;
  cam.position.y = Math.sin(rotX) * RADIUS * 0.8 + Math.sin(t * 0.2) * 5;
  cam.lookAt(0, 0, 0);

  // Pulse target node
  const ti = NODES.findIndex(n => n.isTarget);
  if (ti >= 0) {{
    const sc = 1 + 0.10 * Math.sin(t * 2.6);
    meshes[ti].scale.setScalar(sc);
  }}

  // Animate point lights gently
  pl1.position.x = Math.sin(t * 0.5) * 100;
  pl1.position.z = Math.cos(t * 0.5) * 100;

  renderer.render(scene, cam);
}})();

window.addEventListener('resize', () => {{
  cam.aspect = innerWidth / innerHeight;
  cam.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
}});
</script></body></html>"""

def section_header(title, subtitle=None):
    st.markdown(f"""
    <div style="background-color: #0f172a; padding: 12px 20px; border-radius: 8px; border-left: 6px solid #4361ee; margin-top: 2rem; margin-bottom: 1.5rem; border: 1px solid #1e293b; box-shadow: 0 4px 6px rgba(0,0,0,0.3);">
        <h3 style="margin: 0; padding: 0; color: #f8fafc; font-weight: 600; font-size: 1.4rem;">{title}</h3>
        {f'<p style="margin: 5px 0 0 0; color: #94a3b8; font-size: 0.95rem;">{subtitle}</p>' if subtitle else ''}
    </div>
    """, unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# APP
# ─────────────────────────────────────────────────────────────────────────────
try:
    data, model, vgae_model, weights_loaded, vgae_loaded = load_everything()
    probs = infer(data, model)
    metrics_df = load_team_metrics()
except Exception as ex:
    st.error(f"Failed to load: {ex}\n\nRun `pip install torch-geometric` and restart.")
    st.stop()

# ── Header & Dataset Overview ──────────────────────────────────────────────
st.title("High-Fidelity Graph Neural Networks for Node Classification on the Cora Network")
st.caption("Mayank Shetty Sreekanth (ms4030) | Lokesh Kota (lk671) | Prajwal Srinivas (ps1458)")
st.caption(f"CS550 · Spring 2026 · Papers: {data.num_nodes:,} | Links: {data.num_edges:,} | Word Features: {data.num_features}")

if not weights_loaded:
    st.warning("Demo mode - `gat_best.pth` not found. Using random weights.")

# ── Primary Performance Metrics ─────────────────────────────────────────────
c1, c2, c3 = st.columns(3)
c1.metric("GCN Accuracy", "89.11%", "+12.5% vs baseline")
c2.metric("GAT Accuracy", "88.56%", "+12.0% vs baseline")
c3.metric("Link AUC-ROC", "0.9345", "+0.33% vs GAE")

# ══════════════════════════════════════════════════════════════════════════
# SECTION 1 — Node Classifier + 3D Graph
# ══════════════════════════════════════════════════════════════════════════
section_header("Node Classification & 3D Ego-Network", "Interactive visualization of 2-hop citation neighborhoods.")
ei = data.edge_index.numpy()

col_left, col_graph = st.columns([1, 2.4], gap="small")

with col_left:
    node_id = st.number_input(
        "Paper Node ID (0–2707)", min_value=0, max_value=2707, value=500, step=1
    )
    st.session_state["node_id"] = node_id

    true_label = CLASSES[data.y[node_id].item()]
    in_test    = bool(data.test_mask[node_id].item())
    degree     = int((ei[0] == node_id).sum())
    pred_idx   = int(probs[node_id].argmax())
    pred_class = CLASSES[pred_idx]
    conf       = float(probs[node_id, pred_idx]) * 100
    correct    = (pred_idx == data.y[node_id].item())

    st.metric(
        "Predicted Class",
        pred_class,
        f"{'✓ Correct' if correct else '✗ Wrong'} · {conf:.1f}%",
    )

    st.markdown("**Node metadata**")
    st.markdown(f"""
| Property | Value |
|---|---|
| True label | `{true_label}` |
| Test set | {'Yes ✓' if in_test else 'No'} |
| Out-degree | `{degree}` |
| Word density | `{int(data.x[node_id].sum())} / 1433` |
""")

    st.markdown("**Class probabilities**")
    prob_md = "| Class | Probability |\n|---|---|\n"
    for idx in np.argsort(probs[node_id])[::-1]:
        pct = float(probs[node_id, idx]) * 100
        prob_md += f"| {CLASSES[idx]} | {pct:.1f}% |\n"
    st.markdown(prob_md)

    nbrs = ei[1][ei[0] == node_id].tolist()
    if nbrs:
        st.markdown(f"**Neighbors ({len(nbrs)})**")
        for nid in nbrs[:6]:
            st.caption(f"Node {nid}  -  {CLASSES[data.y[nid].item()]}")

with col_graph:
    components.html(graph_html(data, probs, node_id), height=700, scrolling=False)

# ══════════════════════════════════════════════════════════════════════════
# SECTION 2 — Explainability
# ══════════════════════════════════════════════════════════════════════════
section_header(f"Explainability: Node {node_id}  →  {pred_class}  ({conf:.1f}%)", "GNNExplainer · Attention Weights · LLM")

# ── Explainability Layout ──────────────────────────────────────────────────
xai_c1, xai_c2, xai_c3 = st.columns(3, gap="large")

# ── Combined Interpretable Neighborhood ─────────────────────────────────────
with xai_c1:
    st.markdown("**Influential Neighbors (GNNExplainer + GAT Attention)**")
    with st.spinner("Analyzing neighborhood influence…"):
        try:
            from explainer import run_gnnexplainer, get_attention_weights
            top_edges, top_features, _ = run_gnnexplainer(model, data, node_id, top_k=8)
            attn = dict(get_attention_weights(model, data, node_id, top_k=15))
            
            xai_md = "| Rank | Neighbor Node | Category | XAI Score | Attention |\n|---|---|---|---|---|\n"
            for rank, (_, dst, score) in enumerate(top_edges):
                cls_name = CLASSES[data.y[dst].item()]
                attn_val = f"{attn.get(int(dst), 0.0):.4f}" if attn else "--"
                xai_md += f"| #{rank+1} | Node {dst} | {cls_name} | {float(score):.3f} | {attn_val} |\n"
            st.markdown(xai_md)
        except Exception as e:
            st.error(f"XAI Pipeline Error: {e}")

with xai_c2:
    st.markdown("**Key Word Features (Topic Signature)**")
    words_md = "| Rank | Word Stem | Importance |\n|---|---|---|\n"
    for rank, (_, name, score) in enumerate(top_features[:8]):
        words_md += f"| #{rank+1} | {name} | {float(score):.3f} |\n"
    st.markdown(words_md)
    
    # ── Mechanistic Evidence ───────────────────────────────────────────────
    from explainer import get_mechanistic_metrics
    m_data = get_mechanistic_metrics(model, data, node_id)
    
    st.markdown("**Mechanistic Evidence (Researcher View)**")
    mc1, mc2 = st.columns(2)
    mc1.metric("Homophily", f"{m_data['homophily']:.2f}", help="Structural consistency: % of neighbors sharing this class.")
    mc2.metric("Attention Focus", f"{m_data['attention_sharpness']:.2f}", help="Model confidence focus on specific neighbors.")

# ── LLM explanation ────────────────────────────────────────────────────────
with xai_c3:
    st.markdown("**LLM Explanation**")
    top_words   = [name for (_, name, _) in top_features[:5]]
    top_nbr_cls = [CLASSES[data.y[e[1]].item()] for e in top_edges[:3]]

    actual_cls = CLASSES[int(data.y[node_id])]
    is_correct = "✓ Correct" if pred_class == actual_cls else "✗ Mistake"
    
    st.code(f"""node_id    = {node_id}
actual_cls = "{actual_cls}"
pred_class = "{pred_class}" [{is_correct}]
confidence = {conf:.1f}%
top_words  = {top_words[:3]}
neighbors  = {top_nbr_cls[:2]}""", language="python")

    if st.button("Generate LLM Explanation", type="primary", key="node_exp_btn"):
        with st.spinner("Calling LLM API…"):
            from llm_explain import generate_explanation
            st.session_state['node_exp_result'] = generate_explanation(
                node_id=node_id, predicted_class=pred_class,
                confidence=conf, top_words=top_words,
                top_neighbor_classes=top_nbr_cls,
                mechanistic_data=m_data
            )
    
    if 'node_exp_result' in st.session_state:
        st.info(st.session_state['node_exp_result'])

# ══════════════════════════════════════════════════════════════════════════
# SECTION 3 — Link Prediction Explorer (Trustworthiness: Controllability)
# ══════════════════════════════════════════════════════════════════════════
section_header("Link Prediction Explorer", "Predicting missing citation links between papers using Variational Graph Auto-Encoders.")

lp_c1, lp_c2 = st.columns([1, 2], gap="large")

with lp_c1:
    st.markdown("**Pair Selection**")
    node_a = st.number_input("Source Paper (Node A)", 0, 2707, 500, key="node_a")
    node_b = st.number_input("Target Paper (Node B)", 0, 2707, 600, key="node_b")
    
    if vgae_loaded:
        with torch.no_grad():
            z = vgae_model.encode(data.x, data.edge_index)
            # Binary inner product decoder
            logits = (z[node_a] * z[node_b]).sum(dim=-1)
            prob = torch.sigmoid(logits).item()
        
        st.metric("Connection Probability", f"{prob*100:.1f}%", 
                  help="Confidence that these two papers should be linked.")
        
        # Check if actual edge exists
        edge_exists = False
        ei_np = data.edge_index.numpy()
        mask = (ei_np[0] == node_a) & (ei_np[1] == node_b)
        if mask.any(): edge_exists = True
        
        if edge_exists:
            st.success("Ground Truth: Link exists in dataset.")
        else:
            st.info("Ground Truth: No direct link in dataset.")
    else:
        st.warning("VGAE weights not found. Link prediction disabled.")

with lp_c2:
    st.markdown("**Link Explainability (xAI)**")
    if st.button("Explain Why?", key="btn_lp_explain"):
        with st.spinner("Analyzing joint embedding space..."):
            from explainer import run_link_explainer
            from llm_explain import generate_link_explanation
            
            top_edges, top_feats, names = run_link_explainer(vgae_model, data, node_a, node_b)
            
            shared_words = [f[1] for f in top_feats[:5]]
            shared_topics = list(set([CLASSES[data.y[node_a].item()], CLASSES[data.y[node_b].item()]]))
            
            st.session_state['lp_explanation'] = generate_link_explanation(
                node_a, node_b, prob*100, shared_words, shared_topics
            )
            st.session_state['lp_top_edges'] = top_edges
            st.session_state['lp_top_feats'] = top_feats

    if 'lp_explanation' in st.session_state:
        st.info(st.session_state['lp_explanation'])
        
        excl1, excl2 = st.columns(2)
        with excl1:
            st.caption("Common Neighbors")
            st.dataframe(pd.DataFrame(st.session_state['lp_top_edges'], columns=["Src", "Dst", "Score"]).head(4), use_container_width=True)
        with excl2:
            st.caption("Semantic Overlap")
            st.dataframe(pd.DataFrame(st.session_state['lp_top_feats'], columns=["ID", "Word", "Weight"]).head(4), use_container_width=True)

# ══════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════
# SECTION 4 — Research Benchmarks & Official Results
# ══════════════════════════════════════════════════════════════════════════
section_header("Research Benchmarks & Official Results", "Official performance metrics from the definitive project report, established via multi-pass training.")

# Row 1: Node Classification and Link Prediction Metrics
rb_c1, rb_c2 = st.columns(2, gap="large")
with rb_c1:
    plot_node = get_plot_path("node_classification_comparison.png")
    if plot_node:
        st.image(plot_node, use_container_width=True)
    else: st.info("Node performance diagnostics awaiting output.")

with rb_c2:
    plot_link = get_plot_path("gae_vgae_comparison.png")
    if plot_link:
        st.image(plot_link, use_container_width=True)
    else: st.info("Link discovery diagnostics awaiting output.")

# Row 2: ROC Curve and Detailed Heatmap
rb_c3, rb_c4 = st.columns(2, gap="large")
with rb_c3:
    plot_roc = get_plot_path("link_prediction_roc.png")
    if plot_roc:
        st.image(plot_roc, use_container_width=True, caption="Link Prediction ROC Curve")
    else: st.info("ROC Curve diagnostics awaiting output.")

with rb_c4:
    plot_table = get_plot_path("gae_vgae_table.png")
    if plot_table:
        st.image(plot_table, use_container_width=True, caption="Detailed Ranking & Threshold Metrics")
    else: st.info("Detailed metrics table awaiting output.")

# ══════════════════════════════════════════════════════════════════════════
# SECTION 5 — Ethics & Fairness Audit (Member 3 Role)
# ══════════════════════════════════════════════════════════════════════════
section_header("Ethics & Fairness Audit", "Analyzing model performance variance across research topics to ensure unbiased classification.")

if st.button("Run Live Fairness Audit", type="secondary"):
    with st.spinner("Analyzing per-class performance gaps..."):
        try:
            from sklearn.metrics import classification_report
            import matplotlib.pyplot as plt
            import seaborn as sns
            
            y_true = data.y[data.test_mask].numpy()
            with torch.no_grad():
                logits = model(data.x, data.edge_index)
                y_pred = logits[data.test_mask].argmax(dim=1).numpy()
            
            report = classification_report(y_true, y_pred, target_names=CLASSES, output_dict=True)
            report_df = pd.DataFrame(report).transpose().iloc[:7]
            report_df['class'] = report_df.index
            
            # ── Improved Visualization ─────────────────────────────────────────
            e1, e2 = st.columns([1.5, 1])
            with e1:
                st.markdown("**Per-Class F1-Score (Bias Detection)**")
                
                # We use Seaborn for premium aesthetics
                fig, ax = plt.subplots(figsize=(8, 4))
                sns.set_style("darkgrid", {"axes.facecolor": "#060818", "figure.facecolor": "#060818"})
                plt.rcParams.update({'text.color': "#e2e8f0", 'axes.labelcolor': "#e2e8f0", 'xtick.color': "#94a3b8", 'ytick.color': "#94a3b8"})
                
                # Identify lowest class for coloring
                min_f1 = report_df['f1-score'].min()
                colors = ['#ff6b6b' if x == min_f1 else '#4361ee' for x in report_df['f1-score']]
                
                sns.barplot(data=report_df, x='f1-score', y='class', palette=colors, ax=ax)
                
                # Adjust limits to highlight variance
                plt.xlim(max(0, report_df['f1-score'].min() - 0.1), min(1.0, report_df['f1-score'].max() + 0.05))
                ax.set_xlabel("F1-Score")
                ax.set_ylabel("")
                
                # Add data labels
                for i, v in enumerate(report_df['f1-score']):
                    ax.text(v + 0.005, i, f"{v:.2f}", color='#e2e8f0', va='center', fontweight='bold')
                
                st.pyplot(fig)
                st.caption("X-axis zoomed to highlight performance variance between research topics.")

            with e2:
                min_class = report_df[report_df['f1-score'] == min_f1].index[0]
                st.markdown("**Fairness Analysis**")
                st.warning(f"Detection: Performance dip identified for **{min_class}**.")
                
                with st.expander("Full Statistical Audit"):
                    st.dataframe(report_df[['precision', 'recall', 'f1-score']].style.highlight_min(axis=0, color='#ef476f'), use_container_width=True)
                    
        except Exception as e:
            st.error(f"Fairness audit failed: {e}")
else:
    st.info("Click the button above to perform a real-time fairness audit on the 7 Cora categories.")

st.markdown("---")

# ══════════════════════════════════════════════════════════════════════════
# SECTION 6 — Robustness Lab (Trustworthiness: Robustness)
# ══════════════════════════════════════════════════════════════════════════
st.subheader("Robustness Lab: Adversarial Stress Test")
st.caption("Evaluating model resilience against intentional structural noise and feature corruption.")

rb_c1, rb_c2 = st.columns([1, 1.2], gap="large")

with rb_c1:
    st.markdown("**Attack Configuration**")
    attack_type = st.radio("Choose Attack Vector", ["Structural (Edge Deletion)", "Semantic (Feature Noise)"])
    intensity = st.slider("Attack Intensity (%)", 0, 40, 10)
    
    if st.button("Run Simulation", type="secondary", key="btn_robustness"):
        with st.spinner("Simulating adversarial perturbations..."):
            import numpy as np
            import pandas as pd
            from robustness import run_stress_test
            
            # ── Fix: Ensure specific intensity is in the simulation ────────────
            sim_rates = sorted(list(set([0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4] + [intensity / 100])))
            atk_key = "structural" if "Structural" in attack_type else "feature"
            
            # ── Fix: Final insurance against explain-mode state leakage ───────
            for m in model.modules():
                if hasattr(m, 'explain'): m.explain = False
            
            results = run_stress_test(model, data, attack_type=atk_key, rates=sim_rates)
            res_df = pd.DataFrame(results)
            res_df["intensity"] = res_df["rate"] * 100
            
            # Record current drop for metrics
            current_acc = res_df[res_df['rate'] == 0]['accuracy'].values[0]
            # Use exact match now that intensity/100 is in the list
            atk_acc = res_df[res_df['rate'] == (intensity / 100)]['accuracy'].values[0]
            drop = (current_acc - atk_acc) * 100

            st.session_state["robustness_results"] = res_df
            st.session_state["robustness_drop"] = drop
            st.session_state["robustness_intensity"] = intensity

if "robustness_results" in st.session_state:
    res_df = st.session_state["robustness_results"]
    drop = st.session_state["robustness_drop"]
    intensity = st.session_state["robustness_intensity"]
    
    with rb_c2:
        st.markdown("**Accuracy Degradation Curve**")
        
        # ── Refined Visualization ──────────────────────────────────────────
        import matplotlib.pyplot as plt
        import seaborn as sns
        
        fig, ax = plt.subplots(figsize=(8, 4))
        sns.set_style("darkgrid", {"axes.facecolor": "#060818", "figure.facecolor": "#060818"})
        plt.rcParams.update({
            'text.color': "#e2e8f0", 'axes.labelcolor': "#e2e8f0", 
            'xtick.color': "#94a3b8", 'ytick.color': "#94a3b8"
        })
        
        # Plot with markers for clarity
        sns.lineplot(data=res_df, x="intensity", y="accuracy", marker="o", markersize=8, 
                     color="#ff6b6b", linewidth=2.5, ax=ax)
        
        # KEY: Zoom the Y-axis to highlight the drop (e.g. from 0.91 to 0.88)
        # We set the scale to focus on the actual variance
        min_acc = res_df['accuracy'].min()
        max_acc = res_df['accuracy'].max()
        padding = (max_acc - min_acc) * 0.2 + 0.02
        plt.ylim(min_acc - padding, max_acc + padding)
        
        ax.set_xlabel("Attack Intensity (%)")
        ax.set_ylabel("Test Accuracy")
        
        st.pyplot(fig)
        st.caption("Chart zoomed to highlight model sensitivity levels (+markers denote simulation points).")
        
        m1, m2 = st.columns(2)
        m1.metric("Degradation", f"-{drop:.1f}%", help=f"Drop in accuracy at {intensity}% noise.")
        
        status = "Robust" if drop < 5 else "Resilient" if drop < 15 else "Fragile"
        status_clr = "green" if status == "Robust" else "orange" if status == "Resilient" else "red"
        m2.markdown(f"Status: <strong style='color:{status_clr};'>{status}</strong>", unsafe_allow_html=True)
        
        st.info(f"Insight: At {intensity}% {attack_type.lower()}, the GAT model retains {(100-drop):.1f}% of its original accuracy.")
else:
    with rb_c2:
        st.info("Configure the attack settings and click 'Run Simulation' to see how the model handles a corrupted citation network.")

st.markdown("---")
st.caption("© 2026 CS550 Cora GNN Project Team · Developed for Option 2: Social Networks Compliance")

